### ISSUE TITLE
Schema Resolution Failed Exception using Da Vinci PAS Structure Definitions

### ISSUE THREAD

**Issue by akiander** [FirelyTeam/Firely.Fhir.ValidationDemo#12]
I downloaded `hl7.fhir.us.davinci-pas@2.0.1` package and its dependencies and attempted to validate one of our sample bundles, but I received the following error message: 

```
Encountered an error while loading schema 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claim-inquiry': Failed to convert ElementDefinition at Claim.careTeam:OverallClaimMember in profile http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claim-inquiry: Invocation of function 'binary.as' is not supported in discriminators.
```

The full error with call stack is as follows:

```
Firely.Fhir.Validation.SchemaResolutionFailedException
  HResult=0x80131500
  Message=Encountered an error while loading schema 'http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claim-inquiry': Failed to convert ElementDefinition at Claim.careTeam:OverallClaimMember in profile http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claim-inquiry: Invocation of function 'binary.as' is not supported in discriminators.
  Source=Firely.Fhir.Validation.Compilation
  StackTrace:
   at Firely.Fhir.Validation.Compilation.StructureDefinitionToElementSchemaResolver.GetSchema(Canonical schemaUri)
   at Firely.Fhir.Validation.MultiElementSchemaResolver.GetSchema(Canonical schemaUri)
   at Firely.Fhir.Validation.CachedElementSchemaResolver.GetSchema(Canonical schemaUri)
   at Firely.Fhir.Validation.FhirSchemaGroupAnalyzer.FetchSchema(IElementSchemaResolver resolver, ValidationState state, Canonical canonical)
   at Firely.Fhir.Validation.FhirSchemaGroupAnalyzer.<>c__DisplayClass1_0.<FetchSchemas>b__0(Canonical c)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Firely.Fhir.Validation.FhirSchemaGroupAnalyzer.FetchSchemas(IElementSchemaResolver resolver, ValidationState state, Canonical[] canonicals)
   at Firely.Fhir.Validation.ResourceSchema.ValidateInternal(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ResourceSchema.ValidateInternal(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ResourceSchema.<>c__DisplayClass3_0.<ValidateInternal>b__0(IScopedNode i, Int32 index)
   at System.Linq.Enumerable.<SelectIterator>d__229`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firely.Fhir.Validation.ResourceSchema.ValidateInternal(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.SchemaReferenceValidator.Validate(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.ValidateMany(IAssertion assertion, IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ElementSchema.<>c__DisplayClass19_0.<ValidateInternal>b__0(IAssertion ma)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at Firely.Fhir.Validation.ElementSchema.ValidateInternal(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ElementSchema.Firely.Fhir.Validation.IGroupValidatable.Validate(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.ValidateMany(IAssertion assertion, IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ChildrenValidator.<>c__DisplayClass13_0.<Validate>b__0(Match m)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Firely.Fhir.Validation.ChildrenValidator.Validate(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.<>c__DisplayClass4_0.<ValidateMany>b__2(IScopedNode ma, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__229`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firely.Fhir.Validation.AssertionValidators.<ValidateMany>g__repeat|4_0(IValidatable assertion, IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.ValidateMany(IAssertion assertion, IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ElementSchema.<>c__DisplayClass19_0.<ValidateInternal>b__0(IAssertion ma)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at Firely.Fhir.Validation.ElementSchema.ValidateInternal(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ElementSchema.Firely.Fhir.Validation.IGroupValidatable.Validate(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.ValidateMany(IAssertion assertion, IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ChildrenValidator.<>c__DisplayClass13_0.<Validate>b__0(Match m)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at Firely.Fhir.Validation.ChildrenValidator.Validate(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.ValidateOne(IAssertion assertion, IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ElementSchema.<>c__DisplayClass21_0.<ValidateInternal>b__0(IAssertion ma)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at Firely.Fhir.Validation.ElementSchema.ValidateInternal(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.FhirSchema.ValidateInternal(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ResourceSchema.<>n__0(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ResourceSchema.<>c__DisplayClass5_0.<ValidateResourceSchema>b__0()
   at Firely.Fhir.Validation.ValidationLogger.Start(ValidationState state, String profileUrl, Func`1 validator)
   at Firely.Fhir.Validation.ResourceSchema.ValidateResourceSchema(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ResourceSchema.<>c__DisplayClass4_0.<ValidateInternal>b__6(ResourceSchema s)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at Firely.Fhir.Validation.ResourceSchema.ValidateInternal(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.ResourceSchema.<>c__DisplayClass3_0.<ValidateInternal>b__0(IScopedNode i, Int32 index)
   at System.Linq.Enumerable.<SelectIterator>d__229`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Firely.Fhir.Validation.ResourceSchema.ValidateInternal(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.SchemaReferenceValidator.Validate(IEnumerable`1 input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.SchemaReferenceValidator.Validate(IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.ValidateOne(IAssertion assertion, IScopedNode input, ValidationSettings vc, ValidationState state)
   at Firely.Fhir.Validation.AssertionValidators.Validate(IAssertion assertion, IScopedNode input, ValidationSettings vc)
   at Firely.Fhir.Validation.Validator.Validate(IScopedNode sn, String profile)
   at Firely.Fhir.Validation.Validator.Validate(Resource instance, String profile)

```

These packages worked when using the [Hl7.Fhir.Validation.Legacy library](https://github.com/FirelyTeam/Hl7.Fhir.Validation.Legacy), but I'm experiencing this error when attempting to use [the new firely-validator-api library](https://github.com/FirelyTeam/firely-validator-api). 

Can you confirm that you can validate bundles using this package? If so, do you know what I'm doing incorrectly? 

Here is the bundle we used which contains validation errors that we expected to see: 

[DaVinciPasInquiryRequestBundle.json](https://github.com/FirelyTeam/Firely.Fhir.ValidationDemo/files/13965273/DaVinciPasInquiryRequestBundle.json)

**Comment by ewoutkramer** [comment]
In contrast to the old validator, the new validator is doing a full compilation of the StructureDefinition first, and will report any issues it sees that may cause it to malfunction when actually validating.  This means that the older validator will have swallowed this mistake in the DaVinci profile (which it is), while the new validator signals the mistake.

So what's going on? The exception reads:

> "Invocation of function 'binary.as' is not supported in discriminators."

It seems that profile `http://hl7.org/fhir/us/davinci-pas/StructureDefinition/profile-claim-inquiry` uses slicing with an illegal discriminator. Indeed, when we look at the profile it reads:

```
<element id="Claim.careTeam">
   <path value="Claim.careTeam"/>
   <slicing>
     <discriminator>
       <type value="value"/>
       <path value="extension('http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-careTeamClaimScope').value as boolean"/>
     </discriminator>
     <description value="Slice based on whether the care team member belongs to the overall claim or to an individual claim item."/>
     <rules value="open"/>
  </slicing>
```

The discriminator FhirPath expression `extension('http://hl7.org/fhir/us/davinci-pas/StructureDefinition/extension-careTeamClaimScope').value as boolean` uses the FhirPath `as` operator, which is not allowed in slicing discriminators, according to https://hl7.org/fhir/fhirpath.html#simple.

If this is all Greek to you, that's fair, but we need to signal the authors of this profile, since it is incorrect according to the latest (R5) version of the spec (and previous versions as well ;-).

But that, is ultimately, why the new validator refuses to compile this profile!

**Comment by ewoutkramer** [comment]
I have reported this to the authors of the DaVinci PAS specification: https://jira.hl7.org/browse/FHIR-43913
